# Generated by Django 4.0.1 on 2022-01-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='abs_path',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='path',
        ),
        migrations.AddField(
            model_name='directory',
            name='abs_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesys.directory'),
        ),
    ]
