# Generated by Django 4.0.1 on 2022-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0002_rename_path_file_abs_path_remove_directory_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
